app = "ztr-runtime"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
