apiVersion: apps/v1
kind: Deployment
metadata:
  name: stc-app
  namespace: securethecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stc-app
  template:
    metadata:
      labels:
        app: stc-app
    spec:
      containers:

      # 🔒 APPLICATION
      - name: app
        image: cloudlabxx/stc-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
          - name: REDIS_URL
            value: "redis://redis:6379"
          - name: ZTR_JWT_SECRET
            value: "dev-secret-key"
          - name: POLICY_REVISION
            value: "dev-1"

      # 🔒 OPA SIDECAR
      - name: opa
        image: openpolicyagent/opa:latest
        args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "/policies/issue.rego"
          - "/policies/ztr_introspect.rego"
        volumeMounts:
          - name: opa-policies
            mountPath: /policies

      volumes:
        - name: opa-policies
          configMap:
            name: opa-policy-bundle
